try{
    let ;
}catch(e){
    console.log(`Error is : ${e}`);
}